### PR TITLE
Consolidated installer and executable and added enable function

### PR DESCRIPTION
**Pull request by framps**
Because both scripts were merged a lot of changes were required. This makes merge of new code based on the current master challenging. Sorry about this.

### CODE REVIEW

**Comment by ajacobsen** [comment]
I run a few tests later, update the readme and then I'll merge this. (Except if I find any bugs ofc ;))
github says it can be merged automatically

**Comment by framps** [comment]
I always create a pull request which can just be merged :-) I don't delegate the merge effort to the code owner. Maybe you just wait until I pushed the implemention of enable. Just working on it :-D

**Comment by framps** [comment]
Just finished implementing and adding the enable function.

**Review by ajacobsen — COMMENTED** [review]
You made GIT_INSTALL_URL point to your fork, was that intentional? (line 13)

**Comment by framps** [comment]
Opps .. that's my fault. In order to test the whole path I had to use my git repo. Commented out the reference to my repo

**Pull request merged**
